### ISSUE TITLE
Define methods via Prototypes

### ISSUE THREAD

**Issue by nakaz** [edsperanto/DevLeague--js-constructors#1]
While defining a property within the class with a value that is a function is correct, it is not good practices for `es5` -- let's build them on its respective `prototype` instead. 

We'll get into more cooler stuff in defining methods soon!

Please fix these and push it up! 

https://github.com/edsperanto/DevLeague--js-constructors/blob/master/constructors.js#L25-L27

https://github.com/edsperanto/DevLeague--js-constructors/blob/master/constructors.js#L90-L96

https://github.com/edsperanto/DevLeague--js-constructors/blob/master/constructors.js#L107-L113

https://github.com/edsperanto/DevLeague--js-constructors/blob/master/constructors.js#L140-L162

**Comment by ed-scaped** [comment]
commit id: a7907ec
